modelSettings:
  protocol: modbus
  processName: P_CINERGIA_EL_20_DEV6 # required

c2monSettings: # required
  clientAddress: 192.168.111.77 # required
  clientPort: 30203 # optional, 61616 is the default port number
  #daqAddress: # optional
  #daqPort: # optional

# settings for the modbus device
equitments:
  - equipmentName: E_CINERGIA_EL_20_DEV6 # required
    modelName: CinergiaEl20_DEV6 # required, will be in front of the tag name
    interval: 1000 # optional, time in milliseconds for refreshing all data tags
    address: 172.16.0.81 # required
    modelVersion: 0.0.1 # optional
    port: 502 # required
    unitID: 1 # optional but required? for load simulator device

    # define all signals (data and commands) provided by the modbus interface
    signals: # required
      # Data tags
      - name: Alarm_Vector_ABR # required
        datatype: s64 # optional, data type defined by SourceDataType enum
        description: ERROR ALARM WORD INPUT # optional
        method: read # required type can be one of the following words: [read,write]
        register: holding32 # required; read => [holding] write => [holding]
        startAddress: 13000 # required

      - name: SW_GrafcetState # required
        min: 0
        max: 4294967296
        offset: 0.0 #default 0.0 -> (value * multiplier + offset)
        multiplier: 1.0 #default 1.0 -> (value * multiplier + offset)
        datatype: s64 # optional, data type defined by SourceDataType enum
        description: STATUS WORD INPUT # optional
        method: read # required type can be one of the following words: [read,write]
        register: holding32 # required; read => [holding] write => [holding]
        startAddress: 16000 # required

  - equipmentName: E_CINERGIA_EL_20_DEV6 # required
    modelName: CinergiaEl20_DEV6 # required, will be in front of the tag name
    interval: 1000 # optional, time in milliseconds for refreshing all data tags
    address: 172.16.0.81 # required
    modelVersion: 0.0.1 # optional
    port: 502 # required
    unitID: 1 # optional but required? for load simulator device

    # define all signals (data and commands) provided by the modbus interface
    signals: # required
      # Data tags
      - name: Alarm_Vector_ABR # required
        datatype: s64 # optional, data type defined by SourceDataType enum
        description: ERROR ALARM WORD INPUT # optional
        method: read # required type can be one of the following words: [read,write]
        register: holding32 # required; read => [holding] write => [holding]
        startAddress: 13000 # required

      - name: SW_GrafcetState # required
        min: 0
        max: 4294967296
        offset: 0.0 #default 0.0 -> (value * multiplier + offset)
        multiplier: 1.0 #default 1.0 -> (value * multiplier + offset)
        datatype: s64 # optional, data type defined by SourceDataType enum
        description: STATUS WORD INPUT # optional
        method: read # required type can be one of the following words: [read,write]
        register: holding32 # required; read => [holding] write => [holding]
        startAddress: 16000 # required